### ISSUE TITLE
Doesn't show up in package control

### ISSUE THREAD

**Issue by sheabunge** [wycks/SublimeText-WordPress-Autocomplete#1]
Searching for _WordPress Auto Complete_ in Package Control returns no results. https://sublime.wbond.net/search/WordPress%20Auto%20Complete

**Comment by wycks** [comment]
ya heh I have not added it yet, wanted to test it first.

**Comment by wycks** [comment]
This is now pending due to https://github.com/wbond/package_control_channel/pull/1749

**Comment by sheabunge** [comment]
Oh, okay. I was just confused by the readme. I guess I'll continue using the original WordPress package until this is settled.
