### ISSUE TITLE
Merge Snippets from ninnypants/WordPress-Sublime-Completions

### ISSUE THREAD

**Issue by ninnypants** [wycks/SublimeText-WordPress-Autocomplete#2]
Would you be interested in merging in snippets from the completions plugin that I've been maintaining. https://github.com/ninnypants/WordPress-Sublime-Completions I've been migrating the purplefish snippets over to a better format for remembering them and removing ones that don't make sense. The ones I've been writing follow a simple rule of using actual function names for the snippet eg. `wp_nav_menu` expands with all the args as completion targets.

``` php
wp_nav_menu( array(
    'theme_location' => '',
    'menu' => ,
    'container' => 'div',
    'container_class' => 'menu-{menu slug}-container',
    'container_id' => '',
    'menu_class' => 'menu',
    'menu_id' => '',
    'echo' => true,
    'fallback_cb' => 'wp_page_menu',
    'before' => '',
    'after' => '',
    'link_before' => '',
    'link_after' => '',
    'items_wrap' => '<ul id = "%1$s" class = "%2$s">%3$s</ul>',
    'depth' => 0,
    'walker' => ,
) );
```

Also one other note I've found it easier to work with completions where all non required args are stacked in tab targets so that you con quickly remove all of the remaining args without the potential of leaving commas in.
`{"trigger": "single_cat_title", "contents": "single_cat_title( ${1:${2:\\$prefix = ''}${3:, ${4:\\$display = true}}} )" }`

**Comment by wycks** [comment]
Ya totally that would be awesome! I'm still testing out the autocompletes since I just build a custom parser for it.

**Comment by wycks** [comment]
Oh I just read that second part I totally agree I often just delete the args, I did not know you could nest tags so I'll look into it

**Comment by wycks** [comment]
Added the ability to delete all upon first tab for hook/functions and started to add some snippets, feel free to add more snippets.
